# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/midly/apps/mandelMusicalZoom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/midly/apps/mandelMusicalZoom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midly/apps/mandelMusicalZoom/CMakeFiles /home/midly/apps/mandelMusicalZoom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midly/apps/mandelMusicalZoom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mandelzoom

# Build rule for target.
mandelzoom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mandelzoom
.PHONY : mandelzoom

# fast build rule for target.
mandelzoom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/build
.PHONY : mandelzoom/fast

art.o: art.cpp.o
.PHONY : art.o

# target to build an object file
art.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.cpp.o
.PHONY : art.cpp.o

art.i: art.cpp.i
.PHONY : art.i

# target to preprocess a source file
art.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.cpp.i
.PHONY : art.cpp.i

art.s: art.cpp.s
.PHONY : art.s

# target to generate assembly for a file
art.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.cpp.s
.PHONY : art.cpp.s

aubioParser.o: aubioParser.cpp.o
.PHONY : aubioParser.o

# target to build an object file
aubioParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.cpp.o
.PHONY : aubioParser.cpp.o

aubioParser.i: aubioParser.cpp.i
.PHONY : aubioParser.i

# target to preprocess a source file
aubioParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.cpp.i
.PHONY : aubioParser.cpp.i

aubioParser.s: aubioParser.cpp.s
.PHONY : aubioParser.s

# target to generate assembly for a file
aubioParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.cpp.s
.PHONY : aubioParser.cpp.s

colors.o: colors.cpp.o
.PHONY : colors.o

# target to build an object file
colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.cpp.o
.PHONY : colors.cpp.o

colors.i: colors.cpp.i
.PHONY : colors.i

# target to preprocess a source file
colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.cpp.i
.PHONY : colors.cpp.i

colors.s: colors.cpp.s
.PHONY : colors.s

# target to generate assembly for a file
colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.cpp.s
.PHONY : colors.cpp.s

lodepng.o: lodepng.cpp.o
.PHONY : lodepng.o

# target to build an object file
lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.cpp.o
.PHONY : lodepng.cpp.o

lodepng.i: lodepng.cpp.i
.PHONY : lodepng.i

# target to preprocess a source file
lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.cpp.i
.PHONY : lodepng.cpp.i

lodepng.s: lodepng.cpp.s
.PHONY : lodepng.s

# target to generate assembly for a file
lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.cpp.s
.PHONY : lodepng.cpp.s

mandelzoom.o: mandelzoom.cpp.o
.PHONY : mandelzoom.o

# target to build an object file
mandelzoom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.cpp.o
.PHONY : mandelzoom.cpp.o

mandelzoom.i: mandelzoom.cpp.i
.PHONY : mandelzoom.i

# target to preprocess a source file
mandelzoom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.cpp.i
.PHONY : mandelzoom.cpp.i

mandelzoom.s: mandelzoom.cpp.s
.PHONY : mandelzoom.s

# target to generate assembly for a file
mandelzoom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.cpp.s
.PHONY : mandelzoom.cpp.s

math.o: math.cpp.o
.PHONY : math.o

# target to build an object file
math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.cpp.o
.PHONY : math.cpp.o

math.i: math.cpp.i
.PHONY : math.i

# target to preprocess a source file
math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.cpp.i
.PHONY : math.cpp.i

math.s: math.cpp.s
.PHONY : math.s

# target to generate assembly for a file
math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.cpp.s
.PHONY : math.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mandelzoom"
	@echo "... art.o"
	@echo "... art.i"
	@echo "... art.s"
	@echo "... aubioParser.o"
	@echo "... aubioParser.i"
	@echo "... aubioParser.s"
	@echo "... colors.o"
	@echo "... colors.i"
	@echo "... colors.s"
	@echo "... lodepng.o"
	@echo "... lodepng.i"
	@echo "... lodepng.s"
	@echo "... mandelzoom.o"
	@echo "... mandelzoom.i"
	@echo "... mandelzoom.s"
	@echo "... math.o"
	@echo "... math.i"
	@echo "... math.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

