# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/midly/apps/mandelMusicalZoom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/midly/apps/mandelMusicalZoom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midly/apps/mandelMusicalZoom/CMakeFiles /home/midly/apps/mandelMusicalZoom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midly/apps/mandelMusicalZoom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mandelzoom

# Build rule for target.
mandelzoom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mandelzoom
.PHONY : mandelzoom

# fast build rule for target.
mandelzoom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/build
.PHONY : mandelzoom/fast

# target to build an object file
art.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.o
.PHONY : art.o

# target to preprocess a source file
art.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.i
.PHONY : art.i

# target to generate assembly for a file
art.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/art.s
.PHONY : art.s

# target to build an object file
aubioParser.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.o
.PHONY : aubioParser.o

# target to preprocess a source file
aubioParser.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.i
.PHONY : aubioParser.i

# target to generate assembly for a file
aubioParser.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/aubioParser.s
.PHONY : aubioParser.s

# target to build an object file
colors.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.o
.PHONY : colors.o

# target to preprocess a source file
colors.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.i
.PHONY : colors.i

# target to generate assembly for a file
colors.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/colors.s
.PHONY : colors.s

# target to build an object file
craigsapp-midifile/src/Binasc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Binasc.o
.PHONY : craigsapp-midifile/src/Binasc.o

# target to preprocess a source file
craigsapp-midifile/src/Binasc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Binasc.i
.PHONY : craigsapp-midifile/src/Binasc.i

# target to generate assembly for a file
craigsapp-midifile/src/Binasc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Binasc.s
.PHONY : craigsapp-midifile/src/Binasc.s

# target to build an object file
craigsapp-midifile/src/MidiEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEvent.o
.PHONY : craigsapp-midifile/src/MidiEvent.o

# target to preprocess a source file
craigsapp-midifile/src/MidiEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEvent.i
.PHONY : craigsapp-midifile/src/MidiEvent.i

# target to generate assembly for a file
craigsapp-midifile/src/MidiEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEvent.s
.PHONY : craigsapp-midifile/src/MidiEvent.s

# target to build an object file
craigsapp-midifile/src/MidiEventList.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEventList.o
.PHONY : craigsapp-midifile/src/MidiEventList.o

# target to preprocess a source file
craigsapp-midifile/src/MidiEventList.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEventList.i
.PHONY : craigsapp-midifile/src/MidiEventList.i

# target to generate assembly for a file
craigsapp-midifile/src/MidiEventList.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiEventList.s
.PHONY : craigsapp-midifile/src/MidiEventList.s

# target to build an object file
craigsapp-midifile/src/MidiFile.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiFile.o
.PHONY : craigsapp-midifile/src/MidiFile.o

# target to preprocess a source file
craigsapp-midifile/src/MidiFile.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiFile.i
.PHONY : craigsapp-midifile/src/MidiFile.i

# target to generate assembly for a file
craigsapp-midifile/src/MidiFile.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiFile.s
.PHONY : craigsapp-midifile/src/MidiFile.s

# target to build an object file
craigsapp-midifile/src/MidiMessage.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiMessage.o
.PHONY : craigsapp-midifile/src/MidiMessage.o

# target to preprocess a source file
craigsapp-midifile/src/MidiMessage.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiMessage.i
.PHONY : craigsapp-midifile/src/MidiMessage.i

# target to generate assembly for a file
craigsapp-midifile/src/MidiMessage.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/MidiMessage.s
.PHONY : craigsapp-midifile/src/MidiMessage.s

# target to build an object file
craigsapp-midifile/src/Options.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Options.o
.PHONY : craigsapp-midifile/src/Options.o

# target to preprocess a source file
craigsapp-midifile/src/Options.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Options.i
.PHONY : craigsapp-midifile/src/Options.i

# target to generate assembly for a file
craigsapp-midifile/src/Options.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/craigsapp-midifile/src/Options.s
.PHONY : craigsapp-midifile/src/Options.s

# target to build an object file
lodepng.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.o
.PHONY : lodepng.o

# target to preprocess a source file
lodepng.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.i
.PHONY : lodepng.i

# target to generate assembly for a file
lodepng.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/lodepng.s
.PHONY : lodepng.s

# target to build an object file
mandelzoom.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.o
.PHONY : mandelzoom.o

# target to preprocess a source file
mandelzoom.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.i
.PHONY : mandelzoom.i

# target to generate assembly for a file
mandelzoom.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/mandelzoom.s
.PHONY : mandelzoom.s

# target to build an object file
math.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.o
.PHONY : math.o

# target to preprocess a source file
math.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.i
.PHONY : math.i

# target to generate assembly for a file
math.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/math.s
.PHONY : math.s

# target to build an object file
videoframe.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/videoframe.o
.PHONY : videoframe.o

# target to preprocess a source file
videoframe.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/videoframe.i
.PHONY : videoframe.i

# target to generate assembly for a file
videoframe.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelzoom.dir/build.make CMakeFiles/mandelzoom.dir/videoframe.s
.PHONY : videoframe.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mandelzoom"
	@echo "... art.o"
	@echo "... art.i"
	@echo "... art.s"
	@echo "... aubioParser.o"
	@echo "... aubioParser.i"
	@echo "... aubioParser.s"
	@echo "... colors.o"
	@echo "... colors.i"
	@echo "... colors.s"
	@echo "... craigsapp-midifile/src/Binasc.o"
	@echo "... craigsapp-midifile/src/Binasc.i"
	@echo "... craigsapp-midifile/src/Binasc.s"
	@echo "... craigsapp-midifile/src/MidiEvent.o"
	@echo "... craigsapp-midifile/src/MidiEvent.i"
	@echo "... craigsapp-midifile/src/MidiEvent.s"
	@echo "... craigsapp-midifile/src/MidiEventList.o"
	@echo "... craigsapp-midifile/src/MidiEventList.i"
	@echo "... craigsapp-midifile/src/MidiEventList.s"
	@echo "... craigsapp-midifile/src/MidiFile.o"
	@echo "... craigsapp-midifile/src/MidiFile.i"
	@echo "... craigsapp-midifile/src/MidiFile.s"
	@echo "... craigsapp-midifile/src/MidiMessage.o"
	@echo "... craigsapp-midifile/src/MidiMessage.i"
	@echo "... craigsapp-midifile/src/MidiMessage.s"
	@echo "... craigsapp-midifile/src/Options.o"
	@echo "... craigsapp-midifile/src/Options.i"
	@echo "... craigsapp-midifile/src/Options.s"
	@echo "... lodepng.o"
	@echo "... lodepng.i"
	@echo "... lodepng.s"
	@echo "... mandelzoom.o"
	@echo "... mandelzoom.i"
	@echo "... mandelzoom.s"
	@echo "... math.o"
	@echo "... math.i"
	@echo "... math.s"
	@echo "... videoframe.o"
	@echo "... videoframe.i"
	@echo "... videoframe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

